default_entry: 1
timeout: 3
verbose: yes

/Komodo
    protocol: limine
    kernel_path: boot():/EFI/Boot/KomImage
    kaslr: yes
    cmdline: console=ttyS0
    module_path: boot():/initramfs.cpio
    module_string: initramfs